[package]
name = "iprust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
env_logger = "0.11.0"
log = "0.4.14"
dotenv = "0.15.0"